[[runners]]
  name = "Docker runner 1"
  url = "https://git.lab.karpov.courses/"
  token = "KSwfFYtHmvBDnJN7H6Vi"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/srv/gitlab-runner/data:/srv/gitlab-runner/data", "/certs/client", "/cache"] # << add volums to docker
    shm_size = 0
    network_mode = "host"
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.custom]
    run_exec = ""
